export const CHECK_LOAN_APPLICATION = 'CHECK_LOAN_APPLICATION';

export const LOADING_AUTH_USER = 'LOADING_AUTH_USER';
export const SET_USER_APPLICANT = 'SET_USER_APPLICANT';
export const SET_AUTH_USER_STATUS = 'SET_AUTH_USER_STATUS';

export const CHANGE_GLOBAL_BALANCE = 'CHANGE_GLOBAL_BALANCE';

export const END_LOADING = 'END_LOADING';
